apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: devops-api
        image: my-devops-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: API_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: jwt-algorithm
              key: JWT_ALGORITHM

---
apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 32703
